name: Deploy Frontend to AWS ECS

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "ap-south-1"
      ECS_CLUSTER: "staging-cluster"
      ECS_SERVICE_FRONTEND: "pos-frontend"
      CONTAINER_NAME: "pos-frontend-container" # must match container name in ECS task definition
      IMAGE_TAG: "latest"

    steps:
      # 1️⃣ Checkout Repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Clone `pos-frontend` repository
      - name: Clone pos-frontend Repository
        run: |
          git clone https://github.com/NaveedAliKhan4177/pos-frontend-.git
          ls -l pos-frontend-

      # 3️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 4️⃣ Build & Push Image
      - name: Build and Push Frontend Image
        run: |
          cd pos-frontend-
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:${{ env.IMAGE_TAG }}

      # 5️⃣ Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 6️⃣ Get Current Task Definition
      - name: Get current task definition
        id: task-def
        run: |
          TASK_DEFINITION_ARN=$(aws ecs describe-services \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE_FRONTEND \
            --query "services[0].taskDefinition" \
            --output text)
          echo "task_def_arn=$TASK_DEFINITION_ARN" >> $GITHUB_ENV

      # 7️⃣ Download & Update Task Definition
      - name: Download task definition JSON
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.task_def_arn }} \
            --query "taskDefinition" \
            > task-def.json

      - name: Update task definition with new image
        run: |
          NEW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:${{ env.IMAGE_TAG }}"
          cat task-def.json | jq --arg IMAGE "$NEW_IMAGE" \
            '.containerDefinitions[0].image = $IMAGE' > new-task-def.json

      # 8️⃣ Register New Task Definition
      - name: Register new task definition
        id: register-task-def
        run: |
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)
          echo "new_task_def_arn=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV

      # 9️⃣ Update ECS Service with New Task Definition
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE_FRONTEND \
            --task-definition ${{ env.new_task_def_arn }} \
            --force-new-deployment
